### ISSUE TITLE
Improvements to documentation

### ISSUE THREAD

**Issue by emilydolson** [palaeoware/revosim#14]
As part of my review on the JOSS paper on REvoSim (https://github.com/openjournals/joss-reviews/issues/5284) I have a couple of suggestions for improvements to the documentation. In general, the documentation of all of the features is very thorough. What I think is missing is a layer between the very specific feature documentation and the very general quickstart guide. In particular, it would be really useful to have is a walk-through of the rationale behind the decisions that you make when setting up an experiment in REvoSim. This could be an example of a previous paper done using the platform (I left the "Example usage" box in the JOSS review form unchecked because there doesn't currently  seem to be anything quite like this).

In a similar vein, I think the documentation would benefit from a little more clarification of how certain concepts in REvoSim map onto more general concepts that users may have encountered elsewhere. The two main concepts that I would have loved more clarification on are: 
1) What exactly defines a species? How do new species evolve?
2) How do iterations in this system map onto more generalizable units of time, such as generations. I understand that the exact mapping of iterations to generations depends on the configuration, but a rough ball park would be helpful (or, even better, a display somewhere indicating how many generations have elapsed on average).

**Comment by RussellGarwood** [comment]
Thanks for these suggestions - they have helped us improve the documentation a great deal (the need for such things is harder to spot when you've written the code). 

With above commits there is a new section in the REvoSim docs ["3. Concepts and Example Usage"](https://revosim.readthedocs.io/en/latest/). This includes, in terms of concetps:

1. Introduction to the REvoSim species concept
2. A discussion of how to calculate generation time for any given settings, alongside a few additions to the logging code to make this easier for the user to do

In terms of Example usage, there is now a discussion of the thought process behind the experiments report in Furness et al. (2021). 

Hopefully this addresses both the above requests - I'll leave the issue open for a bit in case there is anything else that would be useful to add, and then close it in a week or so.
